server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: payments-route
              uri: http://payments-api:8080
              predicates:
                - Path=/api/v1/payments,/api/v1/payments/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG